name: Suspect1 - external actions
on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pierotofy/set-swap-space@v1
        with:
          swap-size-gb: 10
      - uses: actions/upload-artifact@v4
        with:
          name: test-artifact
          path: "*.yml"
      - uses: softprops/action-gh-release@v2
        with:
          tag_name: test-tag
          files: "*.yml"
