name: Test Swap Only
on: [push, workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: pierotofy/set-swap-space@v1
        with:
          swap-size-gb: 10
      - run: echo "swap ok"
